repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        # This will auto-format your markdown files
        types_or: [yaml, markdown]

-   repo: https://github.com/errata-ai/vale
    rev: v3.12.0
    hooks:
    -   id: vale
        # This will lint your markdown files using your .vale.ini config
        args: [--config=.vale.ini]
        files: \.md$
