repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
    -   id: prettier
        types_or: [yaml, markdown]

-   repo: https://github.com/errata-ai/vale
    rev: v3.12.0
    hooks:
    -   id: vale
        # This hook runs on every commit.
        args: [--minAlertLevel=error, --config=.vale.ini]
        files: \.md$

-   repo: local
    hooks:
    -   id: vale-sync
        name: vale-sync
        # This is a one-time setup hook, run via `make install`.
        # It downloads the Vale styles into .github/vale/styles
        # so the hook above can find them.
        entry: vale sync
        language: system
        pass_filenames: false
        stages: [manual]
