# Project information
site_name: BitGuides
# The URLs below are set automatically by the deployment workflow.
# They can be left blank here.
site_url:
site_author: S0methingSomething
site_description: Dynamic tutorials for BitEdit.

# Repository
# The URL below is set automatically by the deployment workflow.
# It can be left blank here.
repo_url:

# Copyright
copyright: Copyright &copy; 2025 S0methingSomething

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
