# -----------------------------------------------------------------------------
# Project Configuration
# -----------------------------------------------------------------------------
site_name: BitGuides
site_author: S0methingSomething
site_description: Dynamic tutorials for BitEdit.

# Leave blank if set by the deployment workflow (e.g., GitHub Actions).
site_url:
repo_url:

# -----------------------------------------------------------------------------
# Navigation
# -----------------------------------------------------------------------------
# Define the navigation structure for a predictable user experience.
# nav:
#   - 'Home': 'index.md'
#   - 'Getting Started':
#     - 'Introduction': 'getting-started/introduction.md'
#     - 'Installation': 'getting-started/installation.md'

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png

  # Enforces a single, permanent dark theme.
  palette:
    scheme: slate

  # Features for a modern, mobile-first documentation site.
  features:
    # Navigation & Header
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.tracking

    # Content & Search
    - content.code.copy
    - content.code.wrap
    - search.suggest

# -----------------------------------------------------------------------------
# Metadata & Extensions
# -----------------------------------------------------------------------------
copyright: Copyright © 2025 S0methingSomething

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/S0methingSomething

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
