# -----------------------------------------------------------------------------
# Project Configuration
# -----------------------------------------------------------------------------
site_name: BitGuides
site_author: S0methingSomething
site_description: Guides for modding BitLife.

# Leave blank if set by the deployment workflow.
site_url:
repo_url:

# -----------------------------------------------------------------------------
# Navigation Structure
# -----------------------------------------------------------------------------
nav:
  - 'Home': 'index.md'
  - 'Setting up':
    - 'Requirements': 'setup/requirements.md'
    - 'Setting up ZArchiver': 'setup/zarchiver.md'
  - "Unlocking all BitLife IAP's":
    - 'How to Replace MonetizationVars': 'mod/replacing-monetizationvars.md'
  - 'FAQ': 'mod/faq.md'

# -----------------------------------------------------------------------------
# Theme Configuration
# -----------------------------------------------------------------------------
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    scheme: slate
  features:
    # Navigation & Header
    - header.autohide
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    # Content & Search
    - content.code.copy
    - content.code.wrap
    - search.suggest

# -----------------------------------------------------------------------------
# Metadata & Extensions
# -----------------------------------------------------------------------------
copyright: Copyright © 2025 S0methingSomething | Licensed under the Apache License 2.0

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/S0methingSomething
  # The following keys are automatically updated by the update-links workflow.
  latest_monetization_url: "https://github.com/S0methingSomething/BitEdit/releases/latest"
  latest_reddit_post_url: "https://www.reddit.com/r/BitLifeApp/"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
