site_name: BitGuides
site_url: https://S0methingSomething.github.io/BitGuides/
repo_url: https://github.com/S0methingSomething/BitGuides
repo_name: S0methingSomething/BitGuides
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  latest_monetization_url: "YOUR_FALLBACK_MONETIZATION_URL"
  latest_reddit_post_url: "YOUR_FALLBACK_REDDIT_URL"

nav:
  - 'Home': 'index.md'
  - 'Gameplay':
    - 'Tips': 'gameplay/tips.md'
    - 'How to': 'gameplay/how-to.md'
  - 'Modding':
    - 'MonetizationVars':
      - 'Requirements': 'modding/monetizationvars/requirements.md'
      - 'Unlocking IAP with MonetizationVars': 'modding/monetizationvars/unlocking-iap.md'
    - "APK's":
      - 'WARNING': 'modding/apks/warning.md'
      - 'Mod apk sources': 'modding/apks/sources.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
