# -----------------------------------------------------------------------------
# Project Configuration
# -----------------------------------------------------------------------------
site_name: BitGuides
site_author: S0methingSomething
site_description: Guides for modding BitLife.
repo_url: https://github.com/S0methingSomething/BitGuides

# -----------------------------------------------------------------------------
# Navigation Structure
# -----------------------------------------------------------------------------
nav:
  - 'Home': 'index.md'
  - 'Gameplay':
    - 'Tips': 'gameplay/tips.md'
    - 'How to': 'gameplay/how-to.md'
  - 'Modding':
    - 'MonetizationVars':
      - 'Requirements': 'modding/monetizationvars/requirements.md'
      - 'Unlocking IAP with MonetizationVars': 'modding/monetizationvars/unlock-iap.md' # RENAMED
    - "APK's":
      - 'WARNING': 'modding/apks/warning.md'
      - 'Mod apk sources': 'modding/apks/sources.md'

# -----------------------------------------------------------------------------
# Theme Configuration
# -----------------------------------------------------------------------------
theme:
  name: material
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy

# -----------------------------------------------------------------------------
# Plugins Configuration
# -----------------------------------------------------------------------------
plugins:
  - search
  - link-checker:
      allow_dead_links: false
      # Specifies external links to be ignored by the link-checker plugin.
      # These are managed by a scheduled workflow and may be temporarily invalid.
      dont_check_these_links:
        - https://placeholder.link/monetization
        - https://placeholder.link/reddit

# -----------------------------------------------------------------------------
# Metadata & Extensions
# -----------------------------------------------------------------------------
copyright: Copyright © 2025 S0methingSomething | Licensed under the Apache License 2.0

extra:
  # Custom variables accessible in templates. These are updated by a scheduled workflow.
  latest_monetization_url: "https://placeholder.link/monetization"
  latest_reddit_post_url: "https://placeholder.link/reddit"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
