[project]
name = "bitguides"
version = "0.1.0"
description = "Unofficial general guide for BitLife."
requires-python = ">=3.9"
dependencies = [
    "mkdocs",
    "mkdocs-material",
    "pymdown-extensions",
]
