name: build-and-deploy-docs

on:
  # This section adds the manual trigger
  workflow_dispatch:

  # This section keeps the automatic trigger
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure MkDocs URLs
        env:
          # These variables are automatically provided by GitHub Actions
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          # Dynamically set the repo_url and site_url
          sed -i "s|repo_url:.*|repo_url: https://github.com/${GITHUB_REPOSITORY}|g" mkdocs.yml
          sed -i "s|site_url:.*|site_url: https://${GITHUB_ACTOR}.github.io/${GITHUB_REPOSITORY##*/}/|g" mkdocs.yml
          echo "Updated mkdocs.yml with dynamic URLs"

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
