name: CI Verification
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.13 and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
      - name: Install Python and project dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml
      - name: Install Vale
        run: |
          LATEST_VALE_URL=$(curl -s https://api.github.com/repos/errata-ai/vale/releases/latest | jq -r '.assets[] | select(.name | endswith("Linux_64-bit.tar.gz")) | .browser_download_url')
          curl -sL ${LATEST_VALE_URL} | sudo tar xz -C /usr/local/bin vale
      - name: Sync Vale styles for CI
        run: vale sync
      - name: Run all pre-commit checks
        run: uv run pre-commit run --all-files