name: CI Verification

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.13 and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv pip install -r requirements.txt  # or use `uv pip install .` if you use PEP 621 (pyproject.toml)

      - name: Setup pre-commit and hooks
        run: |
          make setup
          uv run pre-commit install-hooks

      - name: Run all pre-commit checks
        run: uv run pre-commit run --all-files