name: Deploy to GitHub Pages and Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.13 and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Create venv and install Python dependencies
        run: |
          uv venv
          uv pip install -r pyproject.toml

      - name: Load dynamic link configuration
        uses: antifree/json-to-variables@v1
        with:
          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="${{ env.sources_monetization_asset }}") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy site --project-name=bitguides
          gitHubToken: ${{ secrets.GH_TOKEN }}
