name: Deploy to GitHub Pages and Cloudflare Pages (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python 3.13 and uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - name: Create venv and install Python dependencies
        shell: bash
        run: |
          set -euo pipefail
          uv venv
          if [ -f requirements.txt ]; then
            uv pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            uv pip install -e .
          else
            uv pip install mkdocs
          fi

      - name: Load dynamic link configuration
        uses: antifree/json-to-variables@v1
        with:
          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        shell: bash
        run: |
          set -euo pipefail
          MON_URL=$(curl -sSL "https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest" \
            | jq -r --arg name "${{ env.sources_monetization_asset }}" '.assets[] | select(.name==$name) | .browser_download_url')
          REDDIT_ID=$(curl -sSL "https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }}" \
            | jq -r '.activePostId')
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name '*.md' -print0 | xargs -0 sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g"
          find docs -type f -name '*.md' -print0 | xargs -0 sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g"

          echo "Placeholders replaced."

      - name: Deploy to GitHub Pages (push to gh-pages)
        run: uv run mkdocs gh-deploy --force

      - name: Prepare gh-pages worktree for Cloudflare upload
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin gh-pages:gh-pages
          rm -rf gh-pages-worktree
          git worktree add gh-pages-worktree gh-pages
          echo "Prepared worktree at gh-pages-worktree"

      - name: Publish gh-pages contents to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT }}
          directory: gh-pages-worktree
          branch: gh-pages
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="${{ env.sources_monetization_asset }}") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      # Build the static site for Cloudflare Pages
      - name: Build site with MkDocs
        run: uv run mkdocs build --clean

      # Publish the 'site' directory to Cloudflare Pages (Direct Upload)
      - name: Publish to Cloudflare Pages (production)
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT }}
          directory: site
          # Set to your production branch name for a production deployment
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # Deploy to GitHub Pages as before
      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="'${{ env.sources_monetization_asset }}'") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.28.1'
          command: pages deploy site --project-name=bitguides
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="'${{ env.sources_monetization_asset }}'") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.28.1'
          command: pages deploy site --project-name=bitguides
        env:
          CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          CLOUDFLARE_ACCOUNT_ID: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="'${{ env.sources_monetization_asset }}'") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.28.1'
          command: pages deploy site --project-name=bitguides
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="${{ env.sources_monetization_asset }}") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.28.1'
          command: pages deploy site --project-name=bitguides
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}          filename: 'site_config.json'

      - name: Fetch dynamic links and replace placeholders
        run: |
          MON_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="${{ env.sources_monetization_asset }}") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_path }} | jq -r .activePostId)
          REDDIT_URL="${{ env.links_reddit_base_url }}${REDDIT_ID}/"

          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_monetization }}|${MON_URL}|g" {} +
          find docs -type f -name "*.md" -exec sed -i "s|${{ env.placeholders_reddit }}|${REDDIT_URL}|g" {} +

          echo "Placeholders replaced."

      - name: Build site
        run: uv run mkdocs build

      - name: Deploy to GitHub Pages
        run: uv run ghp-import -n -p -f site

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3'
          command: pages deploy site --project-name=bitguides
          gitHubToken: ${{ secrets.GH_TOKEN }}
