name: Update Dynamic Site Variables

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load configuration from JSON file
        id: load_config
        uses: antifree/json-to-variables@v1
        with:
          filename: 'site_config.json'

      - name: Fetch and Prepare Dynamic Data
        id: fetch_data
        run: |
          MONETIZATION_URL=$(curl -sL https://api.github.com/repos/${{ env.sources_monetization_repo }}/releases/latest | jq -r '.assets[] | select(.name=="${{ env.sources_monetization_asset_name }}") | .browser_download_url')
          REDDIT_ID=$(curl -sL https://raw.githubusercontent.com/${{ env.sources_bot_state_repo }}/${{ env.sources_bot_state_file_path }} | jq -r .activePostId)
          echo "mon_url=${MONETIZATION_URL}" >> $GITHUB_OUTPUT
          echo "reddit_id=${REDDIT_ID}" >> $GITHUB_OUTPUT

      - name: Update mkdocs.yml configuration file
        run: |
          sed -i 's|latest_monetization_url:.*|latest_monetization_url: "${{ steps.fetch_data.outputs.mon_url }}"|g' mkdocs.yml
          sed -i 's|latest_reddit_post_url:.*|latest_reddit_post_url: "${{ env.links_reddit_base_url }}${{ steps.fetch_data.outputs.reddit_id }}/"|g' mkdocs.yml

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(docs): Update dynamic site variables"
          file_pattern: mkdocs.yml
